// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from battlebuddy.djinni

#include "NativeAssembler.hpp"  // my header

namespace djinni_generated {

NativeAssembler::NativeAssembler() : ::djinni::JniInterface<::battlebuddy::Assembler, NativeAssembler>("com/veritas/battlebuddy/Assembler$CppProxy") {}

NativeAssembler::~NativeAssembler() = default;


CJNIEXPORT void JNICALL Java_com_veritas_battlebuddy_Assembler_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::battlebuddy::Assembler>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_veritas_battlebuddy_Assembler_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::battlebuddy::Assembler::create();
        return ::djinni::release(::djinni_generated::NativeAssembler::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
