// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from battlebuddy.djinni

#import "BBAssembler+Private.h"
#import "BBAssembler.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface BBAssembler ()

- (id)initWithCpp:(const std::shared_ptr<::battlebuddy::Assembler>&)cppRef;

@end

@implementation BBAssembler {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::battlebuddy::Assembler>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::battlebuddy::Assembler>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable BBAssembler *)create {
    try {
        auto objcpp_result_ = ::battlebuddy::Assembler::create();
        return ::djinni_generated::Assembler::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto Assembler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto Assembler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<BBAssembler>(cpp);
}

}  // namespace djinni_generated

@end
