// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from battlebuddy.djinni

#import <Foundation/Foundation.h>
@class BBAssembler;


@interface BBAssembler : NSObject

+ (nullable BBAssembler *)create;

@end
