// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from battlebuddy.djinni

#pragma once

#include <memory>

namespace battlebuddy {

class Assembler {
public:
    virtual ~Assembler() {}

    static std::shared_ptr<Assembler> create();
};

}  // namespace battlebuddy
